### PR TITLE
Use methods that trigger ActiveRecord callbacks and validations.

### PR DESCRIPTION
**Pull request by ustasb**
When updating relations, I noticed that my ActiveRecord [callbacks](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html) and [validations](http://api.rubyonrails.org/classes/ActiveRecord/Validations.html) weren't being called. Is this intentional?

[delete](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-delete) doesn't execute callbacks but [destroy](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-destroy) does.

[update_attribute](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attribute) skips validations but [update](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update) does not. Though only foreign keys are being updated, it can be confusing when validations are expected to be run. See [here](http://www.davidverhasselt.com/set-attributes-in-activerecord/) for a nice comparison.
## Update

Decided to only update `destroy`. See comments.

### CODE REVIEW

**Comment by brianjlandau** [comment]
Yes, I agree callbacks should always happen when relating/unrelating. So we should definitely move to using destroy not delete. However, I think running validations isn't expected on these particular actions. How would we present validation errors to the user? In general, I think a record being valid shouldn't be a requirement for changing a relationship.

Would you mind reverting back to `update_attribute`? Also, I will merge this into the `activeadmin-1.0` branch as I only intend to do new work on the next version that will be for ActiveAdmin 1.0.

**Comment by ustasb** [comment]
Sure thing! I can appreciate those points. It looks like `update` is private prior to Rails 4 anyways and causes spec failures on master.

**Comment by ustasb** [comment]
Updated.

**Comment by brianjlandau** [comment]
This has been merged into [`activeadmin-1.0`](https://github.com/vigetlabs/active_admin_associations/tree/activeadmin-1.0): 9fda801b31e002d39e953149a07115f69ab08203

**Pull request closed without merging**
